using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class jellybean_movement : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        //take in random initial speed/direction from dispense initialization, bounce off walls until grabbed by head
        //disappear once in bin, reappear if released with random speed/direction generated by bin

        StartCoroutine("Destroy");
    }

    IEnumerator Destroy() {
        yield return new WaitForSeconds(30f);
        Destroy(this.gameObject);
    }
}
