using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class jellybean_movement : MonoBehaviour
{

    private Rigidbody2D _rb;
    private Vector3 _curVelo;

    // Start is called before the first frame update
    void Start()
    {
        _rb = this.GetComponent<Rigidbody2D>();
        _curVelo = _rb.velocity;
    }

    // Update is called once per frame
    void Update()
    {
        //take in random initial speed/direction from dispense initialization, bounce off walls until grabbed by head
        //disappear once in bin, reappear if released with random speed/direction generated by bin

        _curVelo = _rb.velocity;
        StartCoroutine("Destroy");
    }

    IEnumerator Destroy()
    {
        yield return new WaitForSeconds(30f);
        Destroy(this.gameObject);
    }
}
